// apps/web/src/lib/components/Header.svelte
<script lang="ts">
	import { format, isToday } from 'date-fns';

	let now = new Date();

	// Update time every second
	setInterval(() => {
		now = new Date();
	}, 1000);

	$: time = format(now, 'HH:mm');
	$: dateDisplay = isToday(now)
		? 'Today'
		: format(now, 'EEEE, d MMMM');
</script>

<header class="pt-12 pb-4 px-6 text-center">
	<h1 class="font-display text-3xl font-semibold text-earth-100 tracking-wide">
		Bhakti
	</h1>
	<p class="mt-1 text-earth-400 text-sm">
		{dateDisplay} • {time}
	</p>
</header>

// apps/mobile/src/components/Header.tsx
import React from 'react';
import { View, Text } from 'react-native';
import { format, isToday } from 'date-fns';

export function Header() {
  const now = new Date();
  const time = format(now, 'HH:mm');
  const dateDisplay = isToday(now) ? 'Today' : format(now, 'EEEE, d MMMM');

  return (
    <View className="pt-16 pb-4 px-6 items-center">
      <Text className="text-3xl font-semibold text-earth-100 tracking-wide">
        Bhakti
      </Text>
      <Text className="mt-1 text-earth-400 text-sm">
        {dateDisplay} • {time}
      </Text>
    </View>
  );
}
